FIND_PATH(BERKELIUM_INCLUDE_DIR berkelium/Berkelium.hpp)
FIND_LIBRARY(BERKELIUM_RELEASE_LIBRARY NAMES libberkelium)
FIND_LIBRARY(BERKELIUM_DEBUG_LIBRARY NAMES libberkelium_d)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BERKELIUM DEFAULT_MSG BERKELIUM_RELEASE_LIBRARY BERKELIUM_DEBUG_LIBRARY BERKELIUM_INCLUDE_DIR)

IF(BERKELIUM_FOUND)
  SET(BERKELIUM_LIBRARIES optimized ${BERKELIUM_RELEASE_LIBRARY} debug ${BERKELIUM_DEBUG_LIBRARY})
ENDIF(BERKELIUM_FOUND)
